routes/web.php
    Route::post('/painel/tipo-arma/cadastro', 'ArmaController@storeTipoArma')->name('painel-tipo-arma-cadastro');
    Route::post('/painel/tipo-arma/destroy', 'ArmaController@destroyTipoArma')->name('painel-tipo-arma-destroy');


    //Armas associado:
    Route::get('/painel/arma/minhas-armas', 'ArmaController@minhasArmas')->name('painel-minhas-armas');
    Route::get('/painel/arma/cadastrar-minha-arma', 'ArmaController@cadastroArmaAssoc')->name('painel-minha-arma-cadastro');
    Route::post('/painel/arma/cadastro/assoc',    'ArmaController@storeArmaAssoc')->name('painel-arma-store-assoc');




// CONTA
//--------------------------------------------------------------------------------------------------------//

    // PÁGINAS
    Route::get('/painel/conta/listagem', 'ContaController@listagem')->name('painel-conta-listagem');
    Route::get('/painel/conta/historico/{id}', 'ContaController@historico')->name('painel-conta-historico');
    Route::get('/painel/conta/debitar-creditar/', 'ContaController@debitarCreditar')->name('painel-conta-debitar-creditar');
    Route::get('/painel/conta/anuidade/', 'ContaController@anuidade')->name('painel-conta-anuidade');
    Route::get('/painel/conta/editar/{id}', 'ContaController@editar')->name('painel-conta-editar');

    // REQUESTS
    Route::post('/painel/conta/debitar-creditar/', 'ContaController@debitarCreditarStore')->name('painel-conta-debitar-creditar');
    Route::get('/painel/conta/anuidade/gerar', 'ContaController@anuidadeGerar')->name('painel-conta-anuidade-gerar');
    Route::post('/painel/conta/editar/{id}', 'ContaController@update')->name('painel-conta-update');
    Route::post('/painel/conta/editar/', 'ContaController@destroy')->name('painel-conta-destroy');
    Route::get('/painel/conta/exportacao-completa', 'ContaController@exportacaoCompleta')->name('painel-conta-exportacao-completa');


// JANTA
//--------------------------------------------------------------------------------------------------------//

    // PÁGINAS
    Route::get('/painel/janta/listagem', 'JantaController@listagem')->name('painel-janta-listagem');
    Route::get('/painel/janta/novo-ano', 'JantaController@novoAno')->name('painel-janta-novoano');
    Route::get('/painel/janta', 'JantaController@listagemAssociado')->name('painel-janta-associado');

    //REQUESTS
    Route::post('/painel/janta/listagem', 'JantaController@store')->name('painel-janta-listagem');
    Route::post('/painel/janta/destroy', 'JantaController@destroy')->name('painel-janta-destroy');
    Route::get('/painel/janta/gera-novo-ano/{data}', 'JantaController@gerarNovoAno')->name('painel-janta-gerar-ano');
    Route::get('/painel/janta/download-lista-completa', 'JantaController@downloadLista')->name('painel-janta-associado-download');
    Route::get('/painel/janta/exportacao-completa', 'JantaController@exportacaoCompleta')->name('painel-janta-exportacao-completa');

// JANTA PARTICIPANTES
//--------------------------------------------------------------------------------------------------------//

    //PÁGINAS
    Route::get('/painel/janta/{id}/participantes', 'JantaParticipantesController@participantes')->name('painel-janta-participantes');

    //REQUESTS
    Route::post('/painel/janta/{id}/participantes', 'JantaParticipantesController@store')->name('painel-janta-participantes');
    Route::post('/painel/janta/{id}/participantes/destroy', 'JantaParticipantesController@destroy')->name('painel-janta-participante-destroy');
    Route::post('/painel/janta/{id}/participantes/status-pagou', 'JantaParticipantesController@alteraPagou')->name('painel-janta-participante-pagou');

// JANTA PARTICIPANTES
//--------------------------------------------------------------------------------------------------------//

    //PÁGINAS
    Route::get('/painel/downloads/', 'DownloadController@listagem')->name('painel-download-listagem');
    Route::get('/painel/downloads/arquivos', 'DownloadController@listagemCli')->name('painel-download-listagem-cli');

    //REQUESTS
    Route::post('/painel/downloads/', 'DownloadController@store')->name('painel-download-listagem');
    Route::post('/painel/downloads/destroy', 'DownloadController@destroy')->name('painel-download-destroy');
    Route::get('/painel/downloads/{id}', 'DownloadController@download')->name('painel-download-download');

// DECLARACOES
//--------------------------------------------------------------------------------------------------------//

    //PÁGINAS
    Route::get('/painel/declaracoes', 'DeclaracoesController@listagemCli')->name('painel-declaracoes-listagem-cli');
    Route::get('/validacao-declaracao', 'DeclaracoesController@validacao')->name('painel-declaracoes-validacao');
    Route::get('/validacao-declaracao/{codigo}', 'DeclaracoesController@validacao')->name('painel-declaracoes-validacao-codigo');
    Route::get('/validacaodeclaracao', 'DeclaracoesController@validacao')->name('painel-declaracoes-validacao-old');
    Route::get('/validacaodeclaracao/{codigo}', 'DeclaracoesController@validacao')->name('painel-declaracoes-validacao-old-codigo');
    Route::get('/validacao-declaracao/visualizar-documento/{codigo}', 'DeclaracoesController@viewDocumento')->name('painel-ver-documento');


    //REQUESTS
    Route::get('/painel/declaracoes/filiacao', 'DeclaracoesController@declaracaoFiliacao')->name('painel-declaracoes-filiacao');
    Route::get('/painel/declaracoes/guiatrafego', 'DeclaracoesController@declaracaoGuiaTrafego')->name('painel-declaracoes-guiatrafego');
    Route::get('/painel/declaracoes/ranking', 'DeclaracoesController@declaracaoRanking')->name('painel-declaracoes-ranking');
    Route::get('/painel/declaracoes/habitualidade', 'DeclaracoesController@declaracaoHabitualidade')->name('painel-declaracoes-habitualidade');
    Route::get('/painel/declaracoes/habitualidade-portaria150', 'DeclaracoesController@declaracaoHabitualidadePortaria150')->name('painel-declaracoes-habitualidade-portaria150');
    Route::post('/painel/declaracoes/seguranca-acervo', 'DeclaracoesController@declaracaoSegurancaAcervo');
    Route::get('/painel/declaracoes/compromisso', 'DeclaracoesController@declaracaoCompromisso')->name('painel-compromisso');

    Route::get('/painel/declaracoes/habitualidade-portaria166', 'DeclaracoesController@declaracaoHabitualidadePortaria166')->name('painel-declaracoes-habitualidade-portaria166');
    Route::get('/painel/gerar/habitualidade166', 'DeclaracoesController@gerarDeclaracao166');

    //post





    Route::post('/painel/declaracoes/modalidadeProva', 'DeclaracoesController@declaracaoModalidadeProva')->name('painel-declaracoes-modalidade-prova');

// CARTEIRINHA
//--------------------------------------------------------------------------------------------------------//

    //PÁGINAS
    Route::get('/painel/carteirinha', 'CarteirinhaController@index')->name('painel-declaracoes-carteirinha');

    //REQUESTS
    Route::post('/painel/carteirinha', 'CarteirinhaController@geraCarteirinha')->name('painel-declaracoes-carteirinha');

// BLOG
//--------------------------------------------------------------------------------------------------------//

    Route::resource('noticias', 'NoticiasController');
    Route::resource('categorias','CategoriasController');
    Route::resource('blog', 'BlogController');
    Route::resource('blog.category', 'BlogCategoryController');


// LINKS
//--------------------------------------------------------------------------------------------------------//

    Route::resource('link', 'LinkController');

// API
//--------------------------------------------------------------------------------------------------------//

    // ENVIA EMAIL DE CONTATO
    Route::post('/api/send-email/contato', 'ApiController@emailContato')->name('email-contato');
    // RETORNA O USUÁRIO DO CR INFORMADO
    Route::get('/api/usuario/crtouser', 'ApiController@crToUser')->name('cr-to-user');
    // RETORNA O CR DO USUÁRIO INFORMADO
    Route::get('/api/usuario/usertocr', 'ApiController@userToCr')->name('user-to-user');
    // GERA DATAS DA JANTA
    Route::get('/api/janta/getdatas/{data}', 'ApiController@getDatas')->name('janta-get-datas');
    // ATUALIZA PRIMEIRO LOGIN
    Route::get('/api/firstlogin', 'ApiController@firstLogin')->name('api-firstlogin');
    // HABITUALIDADES POR ANO
    Route::get('/api/getPresencasAno', 'ApiController@presencasAnoAtual')->name('api-presenca-ano');
    // DECLARAÇÕES POR ANO
    Route::get('/api/getDeclaracoesAno', 'ApiController@declaracoesAnoAtual')->name('api-declaracoes-ano');
    // ENVIA EMAIL VENCIMENTO CR
    Route::get('/api/vencimentoCR', 'ApiController@emailVencimento')->name('api-vencimento-cr');

    // DEVELOPER ONLY
//--------------------------------------------------------------------------------------------------------//

    if(env('DEVELOPER', false)){
        // TROCA TIPO DA CONTA DO USUÁRIO DO DESENVOLVEDOR COM ID FIXO 1.
        Route::get('/trocatipoconta', function (){
            $user = \App\User::find(1);
            $user->tipo = $user->tipo == "associado" ? "presidente" : "associado";
            return json_encode($user->save());
        });

        //IMPORTAÇÃO DE CONTAS
        Route::get('/importacao/contas', function (){
            return view('outros.importadorContas');
        })->middleware('auth');
        Route::post('/importacao/contas', 'ApiController@importacaoContas')->middleware('auth');

        // IMPORTAçÂO DE HABITUALIDADES
        Route::get('/importacao/habitualidades', function (){
            return view('outros.importadorHabitualidades');
        })->middleware('auth');
        Route::post('/importacao/habitualidades', 'ApiController@importacaoHabitualidades')->middleware('auth');

        // IMPORTAÇÃO DE JANTAS
        Route::get('/importacao/janta', function (){
            return view('outros.importadorJantas');
        });
        Route::post('/importacao/janta', 'ApiController@importacaoJantas')->middleware('auth');
    }

app/Http/Controllers/NoticiasController.php
<?php

namespace App\Http\Controllers;

use File;
use App\Post;
use App\PostCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File as FacadesFile;
use Illuminate\Support\Facades\Validator;

class NoticiasController extends Controller
{
    public function index()
    {
        $posts = Post::all();
        return view('painel.noticias.listagem', ['posts' => $posts]);
    }

    public function create()
    {
        return view('painel.noticias.cadastro');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'content' => 'required',
            'category_id' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        $post = new Post;
        $post->title = $request->title;
        $post->post_category_id = $request->category_id;
        $post->description = $request->content;
        if ($post->save()) {
            if ($request->file()) {
                FacadesFile::makeDirectory(public_path() . '/images/noticias/' . $post->id, $mode = 0755, $recursive = false, $force = false);
                $request->file('file')->move(public_path() . '/images/noticias/' . $post->id, $request->file('file')->getClientOriginalName());
                $path = '/images/noticias/' . $post->id . '/' . $request->file('file')->getClientOriginalName();
                $post->thumbnail = $path;
                $post->save();
            }
            return redirect()->route('noticias.index')->with(['type' => 'alert-success', 'message' => 'Post criado com sucesso!']);
        }
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $post = Post::find($id);
        return view('painel.noticias.editar', ['post' => $post]);
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'content' => 'required',
            'category_id' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }

        $old_thumb = Post::find($id)->thumbnail;
        if (!empty($old_thumb) && !empty($request->file())) {
            FacadesFile::delete($old_thumb);
        }

        if ($request->file() && $request->file('file')->isValid()) {
            $request->file->storeAs('/noticias' . '/' . $id, $request->file->getClientOriginalName());
            $request->file('file')->move(public_path() . '/images/noticias/' . $id, $request->file('file')->getClientOriginalName());
            $path = '/images/noticias/' . $id . '/' . $request->file('file')->getClientOriginalName();
        }

        $post = Post::find($id);
        $post->title = $request->title;
        $post->post_category_id = $request->category_id;
        $post->description =  $request->content;
        !empty($request->file('file')) ? $post->thumbnail = $path : '';

        if ($post->save()) {
            return redirect()->route('noticias.index')->with(['type' => 'alert-success', 'message' => 'Notícia atualizada com sucesso!']);
        }

        return redirect()->route('noticias.index')->with(['type' => 'alert-error', 'message' => 'Ocorreu um erro!']);
    }

    public function destroy($id)
    {
        $post = Post::find($id);
        if ($post->delete()) {
            return redirect()->route('noticias.index')->with(['type' => 'alert-success', 'message' => 'Notícia deletada com sucesso!']);
        }
        return redirect()->route('noticias.index')->with(['type' => 'alert-error', 'message' => 'Ocorreu um erro!']);
    }
}

resources/views/painel/noticias/categorys/cadastro.blade.php
@extends('layouts.material')
@section('title', 'Categorias - Cadastro')
@section('content')

<div class="card card-nav-tabs">
  <div class="card-header card-header-primary">
      <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
      <div class="nav-tabs-navigation">
        <div class="nav-tabs-wrapper">
          <ul class="nav nav-tabs" data-tabs="tabs">
            <li class="nav-item">
              <a class="nav-link" href="{{route('categorias.index')}}"><i class="material-icons">view_list</i> Listagem de categorias</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{{route('categorias.create')}}"><i class="material-icons">add</i> Cadastrar nova categoria</a>
            </li>
          </ul>
        </div>
      </div>
  </div>
  <div class="card-body ">

    <form method="post" id="new-post" action="{{ route('categorias.store') }}">
      @csrf
      <div class="row">
        <div class="col-12 mx-auto mt-5">
          <div class="form-group">
            <input name="name" type="text" class="form-control" placeholder="Nome categoria">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-right">
          <button type="submit" form="new-post" class="btn btn-success pull-right">Criar</button>
        </div>
      </div>
    </form>

  </div>
</div>

@endsection

resources/views/painel/noticias/categorys/editar.blade.php
@extends('layouts.material')
@section('title', 'Categorias - Editar')
@section('content')

@isset($category)
  <div class="card card-nav-tabs">
      <div class="card-header card-header-primary">
          <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
          <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                  <ul class="nav nav-tabs" data-tabs="tabs">
                      <li class="nav-item">
                          <a class="nav-link" href="{{route('categorias.index')}}"><i class="material-icons">view_list</i> Listagem de categorias</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{route('categorias.create')}}"><i class="material-icons">add</i> Cadastrar nova categoria</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link active" href="#"><i class="material-icons">edit</i>EDITANDO</a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
          <div class="card-body">
              <form method="post" action="{{route('categorias.update', $category->id)}}" enctype="multipart/form-data">
                  @csrf
                  @method('PUT')
                  <input type="hidden" value="{{$category->id}}" name="id">
                  <div class="row">
                    <div class="col-12 col-md-8 mx-auto">
                      <label class="mb-2"><strong>Informações</strong></label>
                      <div class="row">

                        <div class="col-12 mt-3">
                          <div class="form-group bmd-form-group @error('data') has-danger @enderror">
                            <label for="title">Nome categoria*</label>
                            <input type="text" class="form-control" required name="name" value="{{old('name') ? old('name') : $category->name}}">
                            @error('name')<span class="material-icons form-control-feedback">clear</span>@enderror
                          </div>
                        </div>

                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-12 text-right">
                      <button type="submit" class="btn btn-success pull-right">Atualizar</button>
                    </div>
                  </div>
              </form>
          </div>
      </div>
    @else
        <p>Nenhuma categoria encontrada neste endereço. Tente novamente ou volte a listagem de categorias.</p>
    @endisset

@endsection

resources/views/painel/noticias/categorys/listagem.blade.php
@extends('layouts.material')
@section('title', 'Categorias - Listagem')
@section('content')

<div class="card card-nav-tabs">
  <div class="card-header card-header-primary">
      <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
      <div class="nav-tabs-navigation">
          <div class="nav-tabs-wrapper">
              <ul class="nav nav-tabs" data-tabs="tabs">
                  @if(\Illuminate\Support\Facades\Auth::user()->tipo == "presidente" || \Illuminate\Support\Facades\Auth::user()->tipo == "secretario")
                      <li class="nav-item">
                          <a class="nav-link active" href="{{route('noticias.index')}}"><i class="material-icons">view_list</i> Listagem de notícias</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{ route('noticias.create') }}"><i class="material-icons">add</i> Cadastrar novo post</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link active" href="{{route('categorias.index')}}"><i class="material-icons">view_list</i> Listagem de categorias</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{{ route('categorias.create') }}"><i class="material-icons">add</i> Cadastrar nova categoria</a>
                      </li>
                  @endif
              </ul>
          </div>
      </div>
  </div>
  <div class="card-body ">
      <div class="tab-content">
          <div class="table-responsive">
            <table id="tabela-cat" class="w-100 table datatable d-none">
              <thead>
                <tr>
                  <td>NOME</td>
                  <td style="width:100px">OPÇÕES</td>
                </tr>
              </thead>
              <tbody>
                @forelse($categorys as $category)
                  <tr>
                      <td>{{$category->name}}</td>
                      <td class="td-actions text-right">
                          <input id="category_id" type="hidden" value="{{$category->id}}">
                          <a href="{{ route('categorias.edit', $category->id) }}" class="btn btn-success">
                              <i class="material-icons">edit</i>
                          </a>
                          <button type="button" class="btn btn-danger delete">
                              <i class="material-icons">delete</i>
                          </button>
                      </td>
                  </tr>
                @empty
                @endforelse
              </tbody>
            </table>
          </div>
          <div class="row spinner">
              <div class="col-12 text-center">
                  <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
              </div>
          </div>
      </div>
  </div>
</div>
@endsection
@section('script')
  <script>
      $(document).ready(()=>{
          $('button.delete').click(function () {
              var button = $(this);
              Swal.fire({
                  title: 'Você tem certeza que deseja remover essa categoria?',
                  type: 'warning',
                  showCancelButton: true,
                  confirmButtonColor: '#d33',
                  cancelButtonColor: '#c0cdd6',
                  confirmButtonText: 'Sim, remover!',
                  cancelButtonText: 'Cancelar!'
              }).then((result) => {
                  const id = $('#category_id').val()
                  if (result.value) {
                    $.post(`categorias/${id}`, 
                        { 
                            _token: '{{csrf_token()}}', 
                            _method : 'DELETE'
                        }
                    )
                    .done( response =>  {
                        console.log(response)
                        button.parent().parent().find('*').css('text-decoration', 'line-through').hide('slow')
                    })
                    .fail( () => {
                        Swal.fire({
                            title: 'Categoria não pode ser deletada, existe notícias dependentes',
                            type: 'warning',
                            showCancelButton: false,
                            confirmButtonColor: '#c0cdd6',
                            confirmButtonText: 'Ok!',
                        })
                    })
                  }
              })
          });

          configDatatables['initComplete'] = function() {
              $('div.dt-buttons').css('display','none')
              $('#tabela-cat').removeClass('d-none');
              $('div.spinner').remove();
          };

          $('.datatable').DataTable(configDatatables);
      });
  </script>

@endsection